### PR TITLE
Replace lodash with minDash that uses native ES5 functions and ES5-based implementations to reduce overall lib size

### PR DESCRIPTION
**Pull request by yamalight**
New PR for #102.
 
So, I did the basic iteration for DI sort of approach proposed in [old PR](https://github.com/postaljs/postal.js/pull/102).
Have a problem figuring out on how to better do DI for optional user implementation of minDash (e.g. lodash, underscore). 
Do have an approximate approaches for CJS and browser, but have no idea on how to do DI with AMD (as I'd never used it that much).

Proposed browser approach:
```js
// before including postal.js user will need to setup minDash replacement if he wants it
window.postalDash = _;

// then we can adjust postal.js part of browser code to something like

// Browser globals
var _ = window.postalDash || minDash;
root.postal = factory( _, root );
```

Proposed CommonJS approach 1:
```js
// change the way postal.js is required to function, then user can just do this:
var _ = require('lodash');
var postal = require('postal')(_);

// then we can adjust postal.js part of cjs code to something like
module.exports = function(userDash) {
    var _ = userDash || minDash;
    factory( _, this );
};
```

Proposed CommonJS approach 2:
```js
// if we don't want to change the way postal require() behaves, we can use global to pass around var:
global.postalDash = require('lodash');
var postal = require('postal');

// then we can adjust postal.js part of cjs code to something like
var _ = global.postalDash || minDash;
module.exports = factory( _, this );
```

Thoughts?

### CODE REVIEW

**Comment by yamalight** [comment]
just FYI, size comparison of compiled and minified versions of postal included into basic script with browserify:

original:
non-minified: 248K
minified: 67K

mindash with requires() of partial lodash functions:
non-minified: 163K
minified: 64K

mindash with native ES5 functions and ES5-based implementations (this PR code basically):
non-minified: 29K
minified: 15K

seems like there's not that much difference in size when lodash partials are used. only makes sense to replace everything with native implementations.

**Comment by Daveawb** [comment]
I am guessing that @ifandelse would need to throw his cards down on this to get a definitive answer. Looking at this in more depth, to work with AMD modules, minDash would need to be AMD ready itself, similar to how postal.js currently wraps itself up as an AMD module. A require call on an AMD module that does not exist will error.

requirejs has a few ways of finding out if a module is defined or specified.

```javascript
// module defined?
var bool = require.defined('lodash');

// module specified?
var bool = require.specified('lodash');
```

I say requirejs as I don't know if other AMD loaders define these exact ways of checking for existance of a module.

That said a try catch block around a `require('lodash')` call in an AMD env. would catch the error and could be used to load in minDash instead.

**Comment by yamalight** [comment]
Now that I'm thinking, it's actually possible to use same approach 1 as for CJS - to change the init function and inject dep directly through it.
But that would mean that all the old code breaks with this change.

**Comment by ifandelse** [comment]
@Daveawb @yamalight Hey - just a quick heads up that I planning to try and catch up on this thread in depth once I get through some of the machina & lux.js changes I've been working on. Just didn't want you to think i was ignoring you! :-)

**Comment by yamalight** [comment]
@ifandelse cheers! :+1: take your time, my changes are not exactly critical to the project :)

**Comment by stephanebachelier** [comment]
@yamalight I have only concern about your change, which I really like by the way: it's missing unit tests for minDash.

**Comment by yamalight** [comment]
@stephanebachelier that's a good point, totally forgot about it. will add them as soon as I can!

**Comment by yamalight** [comment]
So, I'd added tests for minDash. Had to expose it through `postal.configuration.minDash` to test it somehow. Not sure if that's the best approach, but it got me thinking we can actually use it to allow swapping mindash to user configured lodash during runtime with some small tweaks to code.
I.e. we would use `config.minDash` instead of just `_` everywhere in the code. Then user will have an option to do `postal.configuration.minDash = require('lodash');` right after loading postal to replace minDash with custom library like lodash. Thoughts?

**Comment by jdalton** [comment]
For comments on using [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) to reduce overall lib size see https://github.com/postaljs/postal.js/issues/91#issuecomment-73159144.

**Comment by yamalight** [comment]
closing in favor of #112

**Pull request closed without merging**
