### PR TITLE
fix syntax error on IE8

### PR DESCRIPTION
**Pull request by kaesonho**
@ifandelse it's a minor fix, but I saw a syntax error on IE8.

### CODE REVIEW

**Comment by ifandelse** [comment]
Hi @kaesonho - the contents of the lib directory are built output (generated via gulp), so the changes would have to be made to files under src. In this case, JSCS was formatting the file after the src files were concatenated, apply its rule about `catch` needing to be on its own line (apparently it matches the keyword, regardless if it's a method name). Anyways, this was taken care of in #126 (v1.0.6), thanks!

**Comment by kaesonho** [comment]
embarrassed :sweat_smile: , I didn't check the whole process of the build, just want to quickly init a PR to address the issue, thanks anyway :) good to know it's fixed. :+1:

**Comment by ifandelse** [comment]
@kaesonho No worries :smile:. Also - discovered the issue wasn't actually JSCS's fault. I still had node-beautify in the gulp pipeline, which was the culprit.

**Comment by kaesonho** [comment]
I see, thanks :+1:

**Pull request closed without merging**
