### PR TITLE
getting 'cache' from the wrong 'this' (fixed)

### PR DESCRIPTION
**Pull request by whity**

### CODE REVIEW

**Comment by ifandelse** [comment]
@whity I'm curious as to if you could provide a test case showing that it's using the wrong `this`? The third argument being passed to `_.each()` is the `this` context that should be used inside the each's callback - and in this case it's the postal object itself. The only reason I can think of this not working correctly is if you were to invoke `subscribe` in a way where it's call site wasn't postal. For example:

```javascript
// this will end badly
var subscribeHandle = postal.subscribe;
subscribeHandle( { /* options */ } );
```

**Comment by ifandelse** [comment]
@whity Were you using lodash 4.x? If so - looks like the option to pass the `this` context as the 3rd arg to `_.each` was removed. I'm getting it updated now. :-)

**Comment by whity** [comment]
Hi Jim,

Yes, I'm using lodash 4.x.

**Comment by ifandelse** [comment]
This should be good to go in 1.0.11 (and also 2.0.0 - which is going up in a few).

**Pull request closed without merging**
