### PR TITLE
Update lodash to 4 and fix breaking change

### PR DESCRIPTION
**Pull request by kamilbiela**
Hi, I have checked Your code regarding updating to lodash 4. Only breaking change seems to be different _.debounce behaviour. 

lodash 4 debounce don't accept boolean third parameter. 

This PR adds BC change to postal.js debounce method, basically its this ``if`` part of lodash pasted to postal.js: https://github.com/lodash/lodash/blob/3.10.1/lodash.src.js#L7827 which is missing in version 4: https://github.com/lodash/lodash/blob/4.6.1/lodash.js#L8784

Let me know what do You think about it.

### CODE REVIEW

**Comment by kamilbiela** [comment]
ping @ifandelse

**Comment by ifandelse** [comment]
Hi @kamilbiela - apologies for the delay. About to start a round of travel and have been working 2 jobs...but getting things caught up here is next on my list. Will try to carve out some time this week! :-)

**Comment by kamilbiela** [comment]
@ifandelse awesome! :)

**Comment by kamilbiela** [comment]
ping @ifandelse :)

**Comment by ifandelse** [comment]
@kamilbiela Thanks again! Sorry this took me a bit to get merged. My personal schedule has been very busy over the last few months...but really appreciate the contribution and your patience :)

**Comment by kamilbiela** [comment]
:+1: awesome

**Pull request merged**
