### PR TITLE
Fix paths to lodash v4 libs

### LINKED ISSUE #154: Broken postal.lodash.js
Since the lodash@4 version bump in the postal@1.0.9 update, the postal.lodash.js build is broken. As shown in the `npm run test-lodash` : 
```bash
❯ npm run test-lodash

> postal@2.0.0 test-lodash /Users/thibaut/Code/postal.js
> ./node_modules/mocha/bin/mocha -r spec/helpers/node-lodash-build-setup.js spec

module.js:440
    throw err;
    ^

Error: Cannot find module 'lodash/internal/createPartialWrapper'
```

After some investigation, it seems that the `src/mindash.js` is out of date, as lodash@4.0.0 changed most of its modules paths (the full list of changes is here : https://github.com/lodash/lodash/wiki/Changelog#v400)

For example 
```js
var createPartialWrapper = require( "lodash/internal/createPartialWrapper" );
```
seems to be now
```js
var createPartialWrapper = require( "lodash/_createPartialWrapper" );
```

For people using Webpack or other bundlers with the postal.lodash.js build, I recommend to keep the postal version to 1.0.8 until this is fixed.

### PR DESCRIPTION
**Pull request by jcreamer898**
The v4 lodash libs are package by package now. 
This should fix that and close #154.

### CODE REVIEW

**Comment by jdalton** [comment]
You should stick with the `lodash` package and cherry-picking as it will result in smaller builds than the individual method packages. It also allows you to use something like [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) for even smaller builds.

**Comment by jcreamer898** [comment]
ORLY, ok, will look at that.

**Comment by jcreamer898** [comment]
Better @jdalton?

**Comment by jdalton** [comment]
You'll need to change the `lodash.foo` references to `lodash/foo`.

**Comment by jcreamer898** [comment]
There we go. :)

**Comment by ifandelse** [comment]
@jcreamer898 finally over being sick and traveling (and both together).... catching up on this. More than likely, 2.0.1 will land tomorrow. When that happens, could you rebase and then squash these into one commit?

**Comment by jcreamer898** [comment]
Yessir.

**Comment by jcreamer898** [comment]
@ifandelse should be good to go I think

**Comment by jcreamer898** [comment]
WHOA, hold tight, think I need to fix one more thing....

**Comment by ifandelse** [comment]
@jcreamer898 i noticed the package.json version was set to `^4.12.0` - was that intentional (i.e. - must be 4.12 or better)?

**Comment by jcreamer898** [comment]
Not intentional. I'm having some build issues, realized I forgot to run `npm run test-lodash`. Heh, found a few issues. `_.noConflict` isn't a thing in my branch and also foreach isn't a thing either. Working on it.

**Comment by ifandelse** [comment]
@jcreamer898 I just noticed that, too - and it's an issue in master at the moment as well (oops!). I'm wondering if the noConflict call is necessary in the `src/postal.lodash.js` file. @jdalton - should I still be calling `_.noConflict()` to avoid version clobbering in that file?

**Comment by jcreamer898** [comment]
There's no `lodash/noconflict` in the `npm-packages` branch, the only way to get it is by pulling in all of `lodash`, so that doesn't seem right.

Since you have `mindash`, not sure why we'd need the noConflict honestly?

Also, I'm going to submit a separate PR getting Travis CI working.

**Comment by ifandelse** [comment]
@jcreamer898 agreed - want to update your PR removing the _.noConflict call in postal.lodash? I could do it here, of course, but if you do it, it means you can actually verify the tests pass, etc. on your end (for gulp mocha-lodash)

**Comment by jcreamer898** [comment]
Will do.

**Pull request merged**
