### PR TITLE
Replace lodash with native ES5 functions and ES5-based implementations to reduce lib size

### PR DESCRIPTION
**Pull request by yamalight**
So, that's a PR for #91
I went a bit overboard and removed a lodash completely. 
That reduced the size of the lib to 24kb normal size or 8.4kb minified.

Test are all passing normally, coverage did fell a bit though because of the functions that I'd added to replace lodash stuff (e.g. _.clone, _.isEqual), but not too much.

Let me know if that's too much or if there are more additions needed :)

### CODE REVIEW

**Comment by z0r1k** [comment]
+1

**Comment by stephanebachelier** [comment]
+1 as it seems that postal.js is really being slowed by lodash in my use cases.

**Comment by ifandelse** [comment]
@stephanebachelier what postal version are you on? (and I assume you're using lodash 2.4.1?) if you have any benchmarks you've run, I'd love to check them out. I removed conduit from the postal deps a couple of versions back b/c certain things happening in method pipelines were being de-optimized by V* and FF. Seeing where lodash is slowing you down might help me prioritize this effort, since this PR has fallen behind master and would take a bit of work to sync up...

**Comment by Daveawb** [comment]
@yamalight Like the work but I'm unsure why you've gone down this route as (personally I'd prefer to have the ability to still use the lodash/lazy libraries however I can see it'd also be good to not have to use it). Seeing as the project is structured with an element of dependency injection why not use the pattern to your advantage?

```javascript
(function (root, minDash, factory) {
    // This way you can easily check if lodash is actually available as an AMD module
    // or Common JS and inject that into the factory. If not use the minDash functionality
    // that replicates the lodash code used in the library.
}(this, function() {
    return {
        isNumber : function(toCheck) { ... }
    }
}, function( _, global, undefined) { .... });

**Comment by stephanebachelier** [comment]
@ifandelse I don't have any benchmarks. While profiling my application I've found that publish call could be quite slow mainly because of lots of time in lodash. I'm was quite astonished as I've always heard about using lodash for performance.

I would say that it would be a good option to be able to choose between lodash and native, if possible, as there are some projects now that targets es5 browsers only. 

I understand it might be a huge work so I'll try to come back with some numbers.

**Comment by z0r1k** [comment]
Having no lodash dependencies also help postal to be used/shipped with libraries where you want to keep amount of dependencies low.

**Comment by yamalight** [comment]
@Daveawb good idea! will try to update it in that way soon.
@ifandelse I'll try to update the PR to match the latest commits, also will do it the way @Daveawb suggested, that should make it more flexible.

**Comment by yamalight** [comment]
Looks like ditching all the changes and doing everything from scratch is easier approach now. I'm going to close this PR and do a new one once ready.

**Comment by z0r1k** [comment]
@yamalight It's kinda pity that you force pushed or re-created your postal.js fork repo so ```bower install yamalight/postal.js#94244215326809384d0802862397034bc2c1baea``` will not work anymore :(

**Comment by yamalight** [comment]
@z0r1k I indeed re-created it. since last time I changed the code in the postal.js files, it was quite hard to update to latest master because of the merge conflicts. so, I decided to ditch it and re-write in a better way. 
I hope this PR gets merged soon (or discussed, adjusted and then merged), but for now feel free to use my new fork - I think it will not get merge conflicts that are hard to resolve anymore.

**Comment by ifandelse** [comment]
@z0r1k @stephanebachelier @Daveawb Heads up that #112 has been merged in, which provides a customized lodash build option of postal alongside the standard builds. I'm not entirely ruling out an ES5-only option at some point, it's just a low priority. (Though if anyone wants to take that on, I recommend something similar to @jdalton's approach in how he provided the customized lodash module in the `src/mindash.js` file. I'm very happy with the custom lodash option - given how battle-tested lodash is (and the fact that it's a dep in nearly every project of mine!), I'd say this is a win.

**Comment by yamalight** [comment]
@ifandelse see my PR #110 , uses the same approach but recreates all the functions in ES5. But the size changes between using pure ES5 and modular lodash 3 are so little (as was shown by @jdalton) that it doesn't make too much sense to sacrifice stability of lodash 3 (for older browsers too) for 2-3 kilobytes

**Pull request closed without merging**
